### ISSUE TITLE
Implement toArray

### ISSUE THREAD

**Issue by friedger** [novoda/notils#57]
When the cursor result is small you might want to convert it to an array

**Comment by ouchadam** [comment]
I think there's an ongoing debate to drop the `CursorList` since it isn't a real list!

cc @charroch

**Comment by charroch** [comment]
I would not day drop it but maybe rename it. CursorStream ?
On 23 Mar 2015 9:35 pm, "Adam Brown" <notifications@github.com> wrote:

> I think there's an ongoing debate to drop the CursorList since it isn't a
> real list!
>
> cc @charroch <https://github.com/charroch>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/notils/issues/57#issuecomment-85207049>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by friedger** [comment]
CursorAccessor ?
Am 24.03.2015 08:08 schrieb "Carl-Gustaf Harroch" <notifications@github.com
>:

> I would not day drop it but maybe rename it. CursorStream ?

**Comment by xrigau** [comment]
Cursorer

**Comment by stefanhoth** [comment]
CursorExplorer

**Comment by charroch** [comment]
TypedCursor

On 24 March 2015 at 15:28, Stefan Hoth <notifications@github.com> wrote:

> CursorExplorer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/notils/issues/57#issuecomment-85555185>.
>



-- 
Regards, Carl-Gustaf Harroch | CTO @ Novoda.com
Tel: +44 (0) 7 725 721 005

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by charroch** [comment]
TypedCursorList

On 24 March 2015 at 17:12, carl@novoda.com <carl@novoda.com> wrote:

> TypedCursor
>
> On 24 March 2015 at 15:28, Stefan Hoth <notifications@github.com> wrote:
>
>> CursorExplorer
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/novoda/notils/issues/57#issuecomment-85555185>.
>>
>
>
>
> --
> Regards, Carl-Gustaf Harroch | CTO @ Novoda.com
> Tel: +44 (0) 7 725 721 005
>



-- 
Regards, Carl-Gustaf Harroch | CTO @ Novoda.com
Tel: +44 (0) 7 725 721 005

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by stefanhoth** [comment]
ICursorStreamImplObserver

**Comment by ouchadam** [comment]
Cursor2

**Comment by friedger** [comment]
+1 for TypedCursor
Am 24.03.2015 18:36 schrieb "Adam Brown" <notifications@github.com>:

**Comment by blundell** [comment]
`Cerser`
